#!/usr/bin/env bash

exec 6<&0

id=$(cat /proc/sys/kernel/random/uuid)

tar -x -C /var/tmp/${id} <&6

curl -X PUT -H "Content-Type: application/json" "127.0.0.1:9200/_snapshot/${id}" -d "{\"type\": \"fs\",\"settings\": {\"location\": \"/var/tmp/${id}\",\"compress\": true}}"
curl -X GET -H "Content-Type: application/json" "127.0.0.1:9200/_snapshot/${id}/_all?pretty"
curl -X POST -H "Content-Type: application/json" "127.0.0.1:9200/_all/_close?pretty"
curl -X POST -H "Content-Type: application/json" "127.0.0.1:9200/_snapshot/${id}/backup/_restore?wait_for_completion=true&pretty"
curl -X DELETE -H "Content-Type: application/json" "127.0.0.1:9200/_snapshot/${id}"
rm -rf "/var/tmp/${id}"
